### ISSUE TITLE
Gateway Disabled: eSewa does not support your store currency.

### ISSUE THREAD

**Issue by AbishekSitaula** [shivapoudel/woocommerce-esewa#43]
Hello Developer,
I am having trouble integrating this plugin to my woo-commerce site.

Following is the error:
Gateway Disabled: eSewa does not support your store currency.

I have set the woocommerce currency to Nepalese Rupee (NPR) as KHALTi uses NPR and I am trying to integrated both esewa and khalti. How can I perform the integration?

**Comment by shivapoudel** [comment]
Normally on your store, go to **WooCommerce > Settings > General** page where you will find the currency options section. Please update that currency to *Nepali Rupee (Rs)* just like the below screenshot and you are good to integrate the eSewa gateway.

![image](https://user-images.githubusercontent.com/3774827/94408230-391e3280-0194-11eb-9fe8-c187ad12ba82.png)

But since the Khalti integration had some adaptation to the currency symbol it is showing like the screenshot below. By the way, I have saved this option and surf the **WooCommerce > Settings > Payments > eSewa** and is working correctly. Please lemme know if there is any confusion!

![image](https://user-images.githubusercontent.com/3774827/94410564-3a049380-0197-11eb-8dbc-e445fff0bb9f.png)

**Comment by AbishekSitaula** [comment]
What would be the best way to integrate both?
________________________________

**Comment by AbishekSitaula** [comment]
In the screen shot provided there is Nepalese Rupee but you have quoted to use Nepali Rupee but doing both is not helping as same error occurs.
________________________________

**Comment by shivapoudel** [comment]
@AbishekSitaula If you have activated the khalti integration  plugin, probably you will see the second screenshot options for currency but since its value is also NPR inside so it doesn't matter.

In my test site I have enabled both esewa and khalti plugin and the settings for esewa in payments page is not effected. Do it allows khalti to configure and esewa with the above error notice you have stated.

**Comment by AbishekSitaula** [comment]
So, if I place NPR as currency code it will word for both esewa and Khalti?
________________________________

**Comment by shivapoudel** [comment]
Yeah it should work for both brother :)

**Comment by AbishekSitaula** [comment]
Even though I place NPR as the currency code same error is occuring. Gateway is still disabled.
________________________________

**Comment by AbishekSitaula** [comment]
The plugin is now working. But after payment success request is sent by esewa I get error attached here.


________________________________

**Comment by shivapoudel** [comment]
@AbishekSitaula Can you please share me the screenshot or screencast of this error. This step will help me to understand this as an issue/bug clearly?

**Comment by AbishekSitaula** [comment]
Error link: https://neb.shikshya.net/wc-api/WC_Gateway_eSewa/?payment_status=success&key=wc_order_A39J7JaeEzLo8&oid=SHK-NEB-2244&amt=1000.0&refId=0000EID
________________________________

**Comment by AbishekSitaula** [comment]
How can I fix this error?
________________________________

**Comment by shivapoudel** [comment]
Can you confirm if without integrating khalti this issue/bug is replicable or not?

I will work on it at the coming weekend if it is feasible. Like many people, I have a full-time gig and I just hack on stuff like this on the weekends sometimes.

**Comment by AbishekSitaula** [comment]
Yes I can confirm deactivating all plugin except this and Woocommerce plugin is also causing this error.
________________________________

**Comment by AbishekSitaula** [comment]
The main issue of currency have been solved but new issue has arises. New issue will be created.

**Comment by shivapoudel** [comment]
@AbishekSitaula If you could explain how you have solved the currency-related conflict so that other people trying to resolve the conflict will get a clear idea :)

**Comment by AbishekSitaula** [comment]
Using following code for currency worked for both eSewa and Khalti.
`add_filter( 'woocommerce_currencies', 'add_my_currency' );

function add_my_currency( $currencies ) {
     $currencies['NPR'] = __( 'Nepalese Rupee', 'woocommerce' );
     return $currencies;
}

add_filter('woocommerce_currency_symbol', 'add_my_currency_symbol', 10, 2);

function add_my_currency_symbol( $currency_symbol, $currency ) {
     switch( $currency ) {
          case 'NPR': $currency_symbol = 'Rs.'; break;
     }
     return $currency_symbol;
}`

**Comment by haiker-ship** [comment]
Excuse me sir,I am new to wordpress and facing the problem while integrating.So  we have to place the above mentioned code in code snippet plugin?

**Comment by shivapoudel** [comment]
@haiker-ship Until you face the currency issue because of Khalti and eSewa use, you don't have to add the above code snippet.

**Comment by haiker-ship** [comment]
I have both esewa and khalti enabled in wocommerce but none of them are showing....what should I do?

**Comment by shivapoudel** [comment]
@haiker-ship Set the WooCommerce to Nepali rupee (Rs) first. Is there any notice displayed indicating store currency does not match?

**Comment by haiker-ship** [comment]
Yes sir I have set the currency name and symbol Nepali rupee and Rs respectively in wocommerce.There was such notice shown but after setting the currency to Rs it had worked for some hours..but now its gone..

**Comment by haiker-ship** [comment]
Rs doesnt work sir..while setting Rs esewa generates that error message currency store doesnt match

**Comment by AbishekSitaula** [comment]
> I have both esewa and khalti enabled in wocommerce but none of them are showing....what should I do?

Do you have SSL on your site? SSL is required for both plugin to function.

**Comment by haiker-ship** [comment]
Yes sir it has....the payment gateways appears  for some time and then again gone..

**Comment by shivapoudel** [comment]
Please deactivate khalti and test. If that works try to add the above snippet https://github.com/shivapoudel/woocommerce-esewa/issues/43#issuecomment-703287036

**Comment by haiker-ship** [comment]
Hello sir can you provide me your social handles so I can send some media files

**Comment by shivapoudel** [comment]
@haiker-ship https://www.facebook.com/iamshivapoudel/

**Comment by haiker-ship** [comment]
I have just messaged you sir!
